# SPDX-FileCopyrightText: 2025 Swiss Confederation
#
# SPDX-License-Identifier: MIT

server:
  port: 8190

spring:
  datasource:
    url: "jdbc:postgresql://localhost:5190/identifier-registry-db"
    username: "postgres"
    password: "secret"
  jpa:
    properties:
      hibernate:
        ddl-auto: create
  docker:
    compose:
      enabled: true
      file: compose.yml
